application: lords-of-embar
api_version: 1
threadsafe: 1
runtime: python27
version: pre-alpha
module: default

handlers:
- url: /.*
  script: app.server.wsgi

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

env_variables:
  EMBAR_SESSION: 'dev-session-key-override'
